events { worker_connections 1024; }

http {
    # Arkadaki Docker servislerinin isimleri ve konteyner içi portları
    upstream linear_backend { server linear_service:5001; }
    upstream xgboost_backend { server xgboost_service:5002; }
    upstream lgbm_backend    { server lgbm_service:5003; }

    server {
        listen 80;

        # İsteklerin yönlendirileceği rotalar (Endpoints)
        location /predict/linear {
            proxy_pass http://linear_backend/predict;
        }

        location /predict/xgboost {
            proxy_pass http://xgboost_backend/predict;
        }

        location /predict/lgbm {
            proxy_pass http://lgbm_backend/predict;
        }

        # Sağlık kontrolü için ana rota
        location / {
            return 200 '{"message": "API Gateway is working. Use /predict/linear, /predict/xgboost or /predict/lgbm"}';
            add_header Content-Type application/json;
        }
    }
}