# -*- coding: utf-8 -*-
"""llm veri ön işleme çalışma.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-MR0OX73D1lCJUjDbMwafISYhXEeh9LT
"""

!pip install -q transformers datasets ipywidgets

print("Kütüphaneler başarıyla yüklendi.")

import re                               # Regular expression: metin temizleme için
import pandas as pd                     # Veri çerçevesi (tabular veri) için
import numpy as np                      # Sayısal işlemler için
import matplotlib.pyplot as plt         # Grafik çizimi için
from transformers import AutoTokenizer  # Hugging Face tokenizer sınıfı
from datasets import Dataset            # Hugging Face veri seti sınıfı
import warnings                         # Uyarıları bastırmak için
warnings.filterwarnings('ignore')       # Gereksiz uyarıları kapat

# ipywidgets: etkileşimli arayüz bileşenleri
import ipywidgets as widgets
from IPython.display import display, HTML, clear_output

print("Tüm kütüphaneler içe aktarıldı.")

raw_texts=[[
    "Harika bir gün! ✨🚀 Hadi projeye hemen başlayalım!! 🔥",                     # Çoklu emoji ve ünlem
    "Veri     bilimi   ve   makine   öğrenmesi   gelecektir...",                   # Fazla ve düzensiz boşluklar
    "<div>En güncel model sonuçları:</div>\n<strong>BERT vs GPT</strong>",         # Farklı HTML etiketleri (\n dahil)
    "Kupon Kodu: #NLPT2026, Kazanç: +500TL -- Kaçırma!!",                           # Özel karakterler (hashtag, artı, tire)
    "Detaylar için makaleye göz atın: https://arxiv.org/abs/2301.0000 veya ftp://server", # Farklı URL protokolleri (https, ftp)
    "Aaaayyyyııııııııııııııı çok heyecanlıııııııııım!!! 🎉🎉🎉",                   # Harf uzatmaları (elongated words) ve tekrarlayan emojiler
    "E-posta adresim: test_user@domain.com veya info@ai-tech.co.tr",              # Regex testleri için e-posta adresleri
    "Bize ulaşın: +90 (555) 123-4567 [Dahili: 89]"                                  # Telefon numarası ve parantez/köşeli parantez gürültüsü
]]

for i, text in enumerate(raw_texts):
  display(HTML(f"<b>[{i}]</b> <span style='color:pink;'>{text}</span>"))

def clean_text(text: str) ->str:
  text=re.sub(r'https?://\S+','',text)

  emoji_pattern=re.compile(
   "["
   "\u2728"
   "\U0001F680"
   "\U0001F525"
   "\U0001F389"
   "]+",re.UNICODE)

  text=emoji_pattern.sub('',text)

  text=re.sub(r'([!?.,]){2,}',r'\1',text)

  text=re.sub(r'\s+', ' ', text)
  text=re.sub(r'(.)\1{1,}', r'\1', text)
  text=re.sub(r'<[^>]+>', '', text)

  text=re.sub(r'[^a-zA-Z0-9 ĞİöşüğİÖŞÜ]', '', text)
  text=text.strip()

  return text


print("=" * 70)
print("METİN TEMİZLEME SONUÇLARI")
print("=" * 70)

for i,text in enumerate(raw_texts[0]):
  cleaned = clean_text(text)
  print(f"\n[{i}] ORİJİNAL:  {text}")
  print(f"    TEMİZ:     {cleaned}")

class SimpleBPE:

  def __init__(self,vocab_size: int=50):
    self.vocab_size=vocab_size
    self.merges=[]
    self.vocab={}

  def get_stats(self,word:str) -> dict:
      stats={}
      for i in range(len(word)-1):
          pair=word[i]+word[i+1]
          stats[pair]=stats.get(pair,0) + 1

  def merge_pair(self,word:str,pair:str,new_token:str) ->str:

      result=""
      i=0
      while i < len(word):
         if i < len(word) -1 and word[i] + word[i+1]==pair:
            result +=new_token
         else:
             result +=word[i]
             i += 1
      return result

  def fit(self,corpus:list):
      words=' '.join(corpus).split()

      chars=sorted(set(''.join(words)))
      self.vocab={c: i for i,c in enumerate(chars)}
      next_id=len(self.vocab)
      text=''.join(words)

      print(f"Başlangıç vocab boyutu: {len(self.vocab)}")
      print(f"Hedef vocab boyutu: {self.vocab_size}")
      print(f"Eğitim metni ({len(text)} karakter): {text[:80]}...")
      print("\nBPE birleştirme adımları:")
      print("-" * 50)

      step=0
      while len(self.vocab)< self.vocab_size:
          stats=self.get_stats(text)

          if not stats:
               break

          best_pair=max(stats.items(),key=lambda x: x[1]) [0]

          next,_token=chr(0xE000 + next_id)

          self.merges.append((best_pait,new_token))

          text=self.merge_pair(text, best_pair, new_token)

          self.vocab[new_token] = next_id
          next_id += 1

          step += 1

          if step % 5 == 1 or step <= 3:
              print(f"  Adım {step}: '{best_pair}' -> '{new_token}' (frekans: {stats[best_pair]})")

  print("-" * 50)
  print(f"Son vocab boyutu: {len(self.vocab)}")
  print(f"Toplam birleştirme: {len(self.merges)}")

def tokenize(self,text:str) -> list:
    words = text.split()
    tokens = []

    for word in words:
        current = ' '.join(list(word))
        for pair, new_token in self.merges:
                current = self.merge_pair(current, pair, new_token)
        tokens.extend(current.split())

    return tokens

    corpus = [
    "merhaba dünya",
    "merhaba nasılsın",
    "dünya çok güzel",
    "nasılsın iyi misin",
    "güzel bir gün"
]


bpe = SimpleBPE(vocab_size=35)
bpe.fit(corpus)

print("\n" + "=" * 50)
print("TEST TOKENIZASYONU")
print("=" * 50)

test_text = "merhaba dünya nasılsın"
print(f"Girdi: '{test_text}'")
print(f"Token'lar: {bpe.tokenize(test_text)}")