# -*- coding: utf-8 -*-
"""Decision_Tree_Drug_Example

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1066QnL6UjbrR3gFdR_IM6Z2E3WzF48FY
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier, plot_tree, export_text
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

df = pd.read_csv('drug200.csv')
df.columns = df.columns.str.strip()
print(f"Veri seti boyutu: {df.shape}")
print(f"Sınıf dağılımı:\n{df['Drug'].value_counts()}")

df['Sex'] = df['Sex'].map({'F': 0, 'M': 1})
df['BP'] = df['BP'].map({'LOW': 0, 'NORMAL': 1, 'HIGH': 2})
df['Cholesterol'] = df['Cholesterol'].map({'NORMAL': 0, 'HIGH': 1})

df.head()

X = df.drop('Drug', axis=1)
y = df['Drug']

print(f"Özellik matrisi boyutu: {X.shape}")
print(f"Hedef vektörü boyutu: {y.shape}")

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.30, random_state=42, stratify=y
)

print(f"Eğitim seti: {X_train.shape}")
print(f"Test seti: {X_test.shape}")

model = DecisionTreeClassifier(
    criterion='gini',
    max_depth=None,
    min_samples_split=2,
    min_samples_leaf=1,
    random_state=42
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f"Modelin Doğruluk Oranı (Accuracy): {accuracy:.4f}")
print("\nDetaylı Sınıflandırma Raporu:")
print(classification_report(y_test, y_pred))

cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=model.classes_,
            yticklabels=model.classes_)
plt.title('Drug Tahmini - Confusion Matrix')
plt.xlabel('Modelin Tahmini')
plt.ylabel('Gerçek İlaç')
plt.tight_layout()
plt.show()

plt.figure(figsize=(15,10))
plot_tree(model, feature_names=X.columns, class_names=model.classes_, filled=True, rounded=True)
plt.show()